[package]
name = "epicycle_shape_similarity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
num-traits = "0.2.18"
rustfft = "6.2.0"
